name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Execute for pull request comments only
        if: contains(github.event.comment.body, 'amir')
        run: echo "This is a pull request comment event"

