name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

   job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.comment.body }}
      - run: echo 'hello world'

