name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
  job1:
    if: contains(github.event.comment.body, '/support') 
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3
       - name: Build the Docker image ${{ github.event.comment.body }}
         run: echo 'hello world'



