name: Docker Image CI

on:
  issue_comment:
    types: [created]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - name: Execute for pull request comments only
        if: contains(github.event.comment.body, 'amir')
        run: echo "This is a pull request comment event"

